export const quotes = <string[]>[
    "evening settles over the village as the sun sets casting a warm golden glow on the cobblestone streets children laugh and chase each other in fading light their joy echoing through narrow alleys the smell of fresh bread wafts from a nearby bakery inviting passersby to stop and enjoy a moment of simple pleasure in the distance a dog barks breaking the tranquil silence the day ends as it began with a sense of peace and contentment as the world prepares for rest the stars begin to appear in the night sky shimmering softly while the moon rises high illuminating rooftops below the gentle breeze rustles through trees as leaves fall softly to the ground each one whispering stories of seasons gone by lanterns light up doorsteps and windows casting a soft glow through homes where families gather for evening meals the air is filled with the scents of cooked food and laughter that echoes through open windows as the night deepens shadows grow longer and the streets become quieter with each passing hour the village settles into a peaceful slumber under the watchful gaze of the moon and the twinkling stars that punctuate the dark sky the calm and serenity of the evening provide a perfect backdrop for rest and reflection as the world outside fades away into a tranquil night",
    
    "nightfall brings tranquility to the village as the sun disappears below the horizon painting the sky with hues of orange and pink childrens laughter fades as families begin to gather indoors the aroma of freshly cooked food wafts through open windows mingling with the cool evening air lanterns cast a warm glow on doorsteps and windows illuminating the quiet streets each home becomes a cozy retreat from the darkness outside as shadows grow longer and stars begin to appear the moon rises steadily casting its gentle light over the serene village the gentle breeze rustles through the trees as leaves fall softly to the ground whispering stories of seasons gone by the village settles into a peaceful rhythm with families enjoying their evening meals and the comforting sounds of conversation filling the air the tranquil atmosphere is interrupted only by the occasional distant bark of a dog or the soft murmur of the wind the night is calm and serene with the stars shining brightly in the clear sky and the moon casting a soft light over the rooftops the village sleeps soundly under the watchful gaze of the celestial bodies above",
    
    "sunset transforms the village into a peaceful scene as daylight fades and darkness envelops the streets childrens laughter diminishes as families come together for dinner the scent of cooking food mingles with the cool evening breeze drifting through open windows lanterns light up doorsteps and windows creating a warm glow on the tranquil streets each home becomes a sanctuary from the encroaching night as shadows lengthen and the stars emerge in the sky the moon rises high casting its gentle light over the calm village the serene evening is marked by the rhythmic sounds of crickets chirping and the occasional rustle of leaves in the gentle breeze the sky transitions from vibrant hues of orange and pink to deep shades of blue and indigo as the stars begin to twinkle overhead the village settles into a quiet routine with families gathered around their tables enjoying their meals and sharing stories the calm and peaceful atmosphere provides a perfect end to the day as the night deepens and the world outside fades away into darkness",
    
    "daylight fades away giving rise to a peaceful evening in the village as the sun sets and the sky turns shades of orange and pink childrens voices quiet down as families prepare for their evening meals the aroma of delicious food drifts from open windows mingling with the cool night air lanterns illuminate doorsteps and windows casting a warm glow on the serene streets each home becomes a refuge from the growing darkness outside where shadows stretch and stars begin to shine in the sky the moon rises steadily casting its gentle light over the tranquil village the evening is marked by the comforting sounds of family dinners and the soft murmur of conversation filling the air the sky transitions from vibrant colors to a deep blue as the stars emerge and the moon takes its place in the sky the village settles into a quiet rhythm with the streets growing quieter and the night taking hold the peaceful atmosphere is a perfect backdrop for rest and reflection as the day comes to an end",
    
    "transition to nightfall brings serenity to the village as the sun dips below the horizon painting the sky with vibrant colors childrens laughter fades as families start to settle in for dinner the scent of cooked meals fills the air mixing with the cool evening breeze lanterns light up doorsteps and windows casting a soft glow over the peaceful streets each home becomes a retreat from the encroaching darkness as shadows grow longer and the stars appear in the sky the moon rises high above casting its gentle light over the tranquil village the serene evening is characterized by the comforting sounds of family gatherings and the occasional rustle of leaves in the breeze the sky transitions from shades of orange and pink to deep blue as the stars begin to twinkle the village settles into a quiet routine with families enjoying their meals and sharing stories the night deepens and the world outside fades into darkness providing a peaceful backdrop for rest and relaxation",
    
    "twilight descends upon the village bringing a sense of calm as the sun sets and the sky darkens childrens laughter fades away as families gather indoors for dinner the aroma of freshly cooked food wafts through open windows mingling with the cool night air lanterns light up doorsteps and windows casting a warm glow on the quiet streets each home becomes a cozy retreat from the darkening world outside as shadows lengthen and the stars begin to appear in the sky the moon rises steadily casting its gentle light over the peaceful village the night is marked by the soothing sounds of family dinners and the occasional rustle of leaves in the breeze the sky transitions from vibrant hues to deep blue as the stars emerge and the moon takes its place in the sky the village settles into a tranquil rhythm with the streets growing quieter and the night enveloping the homes in a serene atmosphere the calm and peace of the evening provide a perfect end to the day",
    
    "as dusk settles over the village the streets grow quiet and calm with the setting sun casting a golden hue childrens laughter fades as families prepare for their evening meals the scent of delicious food mingles with the cool evening breeze drifting through open windows lanterns illuminate doorsteps and windows casting a warm glow on the serene streets each home becomes a haven from the growing darkness outside where shadows lengthen and stars begin to shine in the sky the moon rises steadily casting its gentle light over the tranquil village the peaceful evening is characterized by the comforting sounds of family gatherings and the occasional murmur of conversation the sky transitions from vibrant colors to deep blue as the stars emerge and the moon shines brightly above the village the calm and serenity of the night provide a perfect backdrop for rest and reflection as the day comes to an end",
    
    "sunset paints the village in hues of orange and pink as the day turns to night childrens voices fade away as families prepare for their evening meals the aroma of freshly cooked food drifts through open windows mingling with the cool evening breeze lanterns light up doorsteps and windows casting a warm glow on the peaceful streets each home becomes a retreat from the growing darkness outside where shadows stretch and the stars begin to shine in the sky the moon rises high casting its gentle light over the serene village the tranquil evening is marked by the comforting sounds of family dinners and the occasional rustle of leaves in the breeze the sky transitions from vibrant hues to deep blue as the stars begin to twinkle the village settles into a quiet rhythm with the streets growing quieter and the night enveloping the homes in a peaceful atmosphere the calm and serenity of the evening provide a perfect end to the day",
    
    "dusk falls gently over the village transforming the streets into a peaceful scene as the sun sets childrens laughter fades as families come together for dinner the aroma of cooking food mingles with the cool evening air drifting through open windows lanterns light up doorsteps and windows casting a soft glow over the tranquil streets each home becomes a cozy retreat from the encroaching darkness as shadows grow longer and stars begin to appear in the sky the moon rises steadily casting its gentle light over the calm village the serene evening is characterized by the comforting sounds of family dinners and the occasional murmur of conversation the sky transitions from vibrant colors to deep blue as the stars emerge and the moon shines brightly above the village the night deepens and the world outside fades into darkness providing a peaceful backdrop for rest and relaxation",
    
    "evening brings a serene calm to the village as the sun sets and darkness envelops the streets childrens laughter fades as families gather indoors for dinner the scent of food drifts through open windows mingling with the cool night air lanterns illuminate doorsteps and windows casting a warm glow on the tranquil streets each home becomes a refuge from the darkening world outside where shadows stretch and stars begin to shine in the sky the moon rises steadily casting its gentle light over the peaceful village the calming atmosphere is characterized by the soothing sounds of family gatherings and the occasional rustle of leaves in the breeze the sky transitions from shades of orange and pink to deep blue as the stars emerge and the moon takes its place in the sky the village settles into a quiet rhythm with the streets growing quieter and the night enveloping the homes in a serene ambiance the calm and peace of the evening provide a perfect end to the day",
    
    "nightfall brings tranquility to the village as the sun sinks below the horizon painting the sky with vibrant hues of orange and pink childrens laughter fades away as families begin to gather for dinner the aroma of cooked meals wafts through open windows mingling with the cool evening breeze lanterns light up doorsteps and windows casting a warm glow on the serene streets each home becomes a retreat from the encroaching darkness outside where shadows stretch and stars begin to shine in the sky the moon rises steadily casting its gentle light over the tranquil village the evening is marked by the soothing sounds of family dinners and the occasional rustle of leaves in the breeze the sky transitions from vibrant colors to deep blue as the stars emerge and the moon shines brightly above the village the calm and serenity of the night provide a perfect backdrop for rest and relaxation as the day comes to an end",
    
    "dusk settles over the village bringing a sense of calm as the sun sets and the sky darkens childrens laughter fades as families gather indoors for dinner the aroma of freshly cooked food wafts through open windows mingling with the cool night air lanterns light up doorsteps and windows casting a warm glow on the quiet streets each home becomes a cozy retreat from the darkening world outside as shadows lengthen and stars begin to appear in the sky the moon rises steadily casting its gentle light over the peaceful village the tranquil evening is characterized by the comforting sounds of family dinners and the occasional murmur of conversation the sky transitions from vibrant hues to deep blue as the stars emerge and the moon takes its place in the sky the village settles into a serene rhythm with the streets growing quieter and the night enveloping the homes in a peaceful ambiance the calm and serenity of the evening provide a perfect end to the day",
    
    "as dusk falls upon the village the streets grow quiet and calm with the setting sun casting a golden hue childrens laughter fades as families prepare for their evening meals the scent of delicious food mingles with the cool evening breeze drifting through open windows lanterns light up doorsteps and windows casting a warm glow on the serene streets each home becomes a haven from the growing darkness outside where shadows stretch and stars begin to shine in the sky the moon rises steadily casting its gentle light over the tranquil village the peaceful evening is marked by the comforting sounds of family gatherings and the occasional rustle of leaves in the breeze the sky transitions from vibrant colors to deep blue as the stars emerge and the moon shines brightly above the village the calm and serenity of the night provide a perfect backdrop for rest and reflection as the day comes to an end"
  ];